version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "v2"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "nestjs"
        versions: ["*"]
      - dependency-name: "typescript"
        versions: ["*"]
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "v2"
    labels:
      - "dependencies"
      - "github-actions"
